exports.seed = function (knex) {
  return knex('items').del()
    .then(function () {
      return knex('items').insert([
        { id: 1, word: 'all done', image: '/images/Actions/all_done.png', categories_id: 102, tag: 'verb' },
        { id: 2, word: 'drink', image: '/images/Actions/drink.png', categories_id: 102, tag: 'verb' },
        { id: 3, word: 'eat', image: '/images/Actions/eat.png', categories_id: 102, tag: 'verb' },
        { id: 4, word: 'have', image: '/images/Actions/have.png', categories_id: 102, tag: 'verb' },
        { id: 5, word: 'help', image: '/images/Actions/help.png', categories_id: 102, tag: 'verb' },
        { id: 6, word: 'leave', image: '/images/Actions/leave.png', categories_id: 102, tag: 'verb' },
        { id: 7, word: 'play', image: '/images/Actions/play.png', categories_id: 102, tag: 'verb' },
        { id: 8, word: 'quiet', image: '/images/Actions/quiet.png', categories_id: 102, tag: 'adjective' },
        { id: 9, word: 'want', image: '/images/Actions/want.png', categories_id: 102, tag: 'verb' },
        { id: 10, word: 'he', image: '/images/Descriptions/he.png', categories_id: 103, tag: 'pronoun' },
        { id: 11, word: 'her', image: '/images/Descriptions/her.png', categories_id: 103, tag: 'pronoun' },
        { id: 12, word: 'I', image: '/images/Descriptions/i.png', categories_id: 103, tag: 'pronoun' },
        { id: 13, word: 'it', image: '/images/Descriptions/it.png', categories_id: 103, tag: 'pronoun' },
        { id: 14, word: 'me', image: '/images/Descriptions/me.png', categories_id: 103, tag: 'pronoun' },
        { id: 15, word: 'mine', image: '/images/Descriptions/mine.png', categories_id: 103, tag: 'pronoun' },
        { id: 16, word: 'them', image: '/images/Descriptions/them.png', categories_id: 103, tag: 'pronoun' },
        { id: 17, word: 'we', image: '/images/Descriptions/we.png', categories_id: 103, tag: 'pronoun' },
        { id: 18, word: 'brush teeth', image: '/images/activites/brush_teeth.png', categories_id: 107, tag: 'verb' },
        { id: 19, word: 'catch', image: '/images/activites/catch.png', categories_id: 107, tag: 'verb' },
        { id: 20, word: 'conversation', image: '/images/activites/conversation.png', categories_id: 107, tag: 'noun' },
        { id: 21, word: 'dance', image: '/images/activites/dance.png', categories_id: 107, tag: 'verb' },
        { id: 22, word: 'draw', image: '/images/activites/draw.png', categories_id: 107, tag: 'verb' },
        { id: 23, word: 'eat', image: '/images/activites/eat.png', categories_id: 107, tag: 'verb' },
        { id: 24, word: 'hold hands', image: '/images/activites/hold_hands.png', categories_id: 107, tag: 'verb' },
        { id: 25, word: 'homework', image: '/images/activites/homework.png', categories_id: 107, tag: 'noun' },
        { id: 26, word: 'jump rope', image: '/images/activites/jump_rope.png', categories_id: 107, tag: 'noun' },
        { id: 27, word: 'run', image: '/images/activites/run.png', categories_id: 107, tag: 'verb' },
        { id: 28, word: 'pants', image: '/images/clothes/pants.png', categories_id: 108, tag: 'noun' },
        { id: 29, word: 'shorts', image: '/images/clothes/shorts.png', categories_id: 108, tag: 'noun' },
        { id: 30, word: 'swimsuit', image: '/images/clothes/swimsuit.png', categories_id: 108, tag: 'noun' },
        { id: 31, word: 'shirt', image: '/images/clothes/shirt.png', categories_id: 108, tag: 'noun' },
        { id: 32, word: 'sweater', image: '/images/clothes/sweater.png', categories_id: 108, tag: 'noun' },
        { id: 33, word: 'socks', image: '/images/clothes/socks.png', categories_id: 108, tag: 'noun' },
        { id: 34, word: 'underwear', image: '/images/clothes/underwear.png', categories_id: 108, tag: 'noun' },
        { id: 35, word: 'umbrella', image: '/images/clothes/umbrella.png', categories_id: 108, tag: 'noun' },
        { id: 36, word: 'pajamas', image: '/images/clothes/pajamas.png', categories_id: 108, tag: 'noun' },
        { id: 37, word: 'get dressed', image: '/images/clothes/get_dressed.png', categories_id: 108, tag: 'preposition' },
        { id: 38, word: 'angry', image: '/images/help/angry.png', categories_id: 104, tag: 'adjective' },
        { id: 39, word: 'bad', image: '/images/help/bad.png', categories_id: 104, tag: 'adjective' },
        { id: 40, word: 'feel', image: '/images/help/feel.png', categories_id: 104, tag: 'verb' },
        { id: 41, word: 'frustrated', image: '/images/help/frustrated.png', categories_id: 104, tag: 'adjective' },
        { id: 42, word: 'good', image: '/images/help/good.png', categories_id: 104, tag: 'adjective' },
        { id: 43, word: 'happy', image: '/images/help/happy.png', categories_id: 104, tag: 'adjective' },
        { id: 44, word: 'hot', image: '/images/help/hot.png', categories_id: 104, tag: 'adjective' },
        { id: 45, word: 'I have', image: '/images/Quick/i_have.png', categories_id: 101, tag: 'verb' },
        { id: 46, word: 'lost', image: '/images/help/lost.png', categories_id: 104, tag: 'verb' },
        { id: 47, word: 'need help', image: '/images/help/need_help.png', categories_id: 104, tag: 'verb' },
        { id: 48, word: 'sad', image: '/images/help/sad.png', categories_id: 104, tag: 'adjective' },
        { id: 49, word: 'rest', image: '/images/help/rest.png', categories_id: 104, tag: 'verb' },
        { id: 50, word: 'scared', image: '/images/help/scared.png', categories_id: 104, tag: 'adjective' },
        { id: 51, word: 'shocked', image: '/images/help/shocked.png', categories_id: 104, tag: 'adjective' },
        { id: 52, word: 'sick', image: '/images/help/sick.png', categories_id: 104, tag: 'adjective' },
        { id: 53, word: 'thirsty', image: '/images/help/thirsty.png', categories_id: 104, tag: 'adjective' },
        { id: 54, word: 'tired', image: '/images/help/tired.png', categories_id: 104, tag: 'adjective' },
        { id: 55, word: 'too loud', image: '/images/help/too_loud.png', categories_id: 104, tag: 'adjective' },
        { id: 56, word: 'uncomfortable', image: '/images/help/uncomfortable.png', categories_id: 104, tag: 'adjective' },
        { id: 57, word: 'worried', image: '/images/help/worried.png', categories_id: 104, tag: 'adjective' },
        { id: 58, word: 'hurt', image: '/images/help/hurt.png', categories_id: 104, tag: 'verb' },
        { id: 59, word: 'stomach hurts', image: '/images/help/stomach_hurts.png', categories_id: 104, tag: 'verb' },
        { id: 60, word: 'milk', image: '/images/Food/milk.png', categories_id: 106, tag: 'noun' },
        { id: 61, word: 'juice', image: '/images/Food/juice.png', categories_id: 106, tag: 'noun' },
        { id: 62, word: 'hungry', image: '/images/Food/hungry.png', categories_id: 106, tag: 'adjective' },
        { id: 63, word: 'drink', image: '/images/Food/drink.png', categories_id: 106, tag: 'verb' },
        { id: 64, word: 'water', image: '/images/Food/water.png', categories_id: 106, tag: 'noun' },
        { id: 65, word: 'fruit', image: '/images/Food/fruit.png', categories_id: 106, tag: 'noun' },
        { id: 66, word: 'dinner', image: '/images/Food/dinner.png', categories_id: 106, tag: 'noun' },
        { id: 67, word: 'snack', image: '/images/Food/snack.png', categories_id: 106, tag: 'noun' },
        { id: 68, word: 'breakfast', image: '/images/Food/breakfast.png', categories_id: 106, tag: 'noun' },
        { id: 69, word: 'lunch', image: '/images/Food/lunch.png', categories_id: 106, tag: 'noun' },
        { id: 70, word: 'no', image: 'none', categories_id: 109, tag: 'determiner' },
        { id: 71, word: 'yes', image: 'none', categories_id: 109, tag: 'determiner' },
        { id: 72, word: 'sister', image: '/images/People/sister.png', categories_id: 105, tag: 'noun' },
        { id: 73, word: 'babysitter', image: '/images/People/babysitter.png', categories_id: 105, tag: 'noun' },
        { id: 74, word: 'paramedic', image: '/images/People/paramedic.png', categories_id: 105, tag: 'noun' },
        { id: 75, word: 'brother', image: '/images/People/brother.png', categories_id: 105, tag: 'noun' },
        { id: 76, word: 'friend', image: '/images/People/friend.png', categories_id: 105, tag: 'noun' },
        { id: 77, word: 'police', image: '/images/People/police.png', categories_id: 105, tag: 'noun' },
        { id: 78, word: 'mom', image: '/images/People/mom.png', categories_id: 105, tag: 'noun' },
        { id: 79, word: 'you', image: '/images/People/you.png', categories_id: 105, tag: 'pronoun' },
        { id: 80, word: 'doctor', image: '/images/People/doctor.png', categories_id: 105, tag: 'noun' },
        { id: 81, word: 'teacher', image: '/images/People/teacher.png', categories_id: 105, tag: 'noun' },
        { id: 82, word: 'What is your name?', image: '/images/Quick/what_is_your_name.png', categories_id: 105, tag: 'question' },
        { id: 84, word: 'like', image: '/images/Quick/like.png', categories_id: 101, tag: 'verb' },
        { id: 85, word: 'need', image: '/images/Quick/need.png', categories_id: 101, tag: 'verb' },
        { id: 86, word: 'okay', image: '/images/Quick/okay.png', categories_id: 101, tag: 'determiner' },
        { id: 87, word: 'out', image: '/images/Quick/out.png', categories_id: 101, tag: 'preposition' },
        { id: 88, word: 'please', image: '/images/Quick/please.png', categories_id: 101, tag: 'question' },
        { id: 89, word: 'thank you', image: '/images/Quick/thank_you.png', categories_id: 101, tag: 'conjunction' },
        { id: 90, word: 'wait', image: '/images/Quick/wait.png', categories_id: 101, tag: 'verb' },
        { id: 91, word: 'what', image: '/images/Quick/what.png', categories_id: 101, tag: 'determiner' },
        { id: 92, word: 'and', image: '/images/Quick/and.png', categories_id: 101, tag: 'preposition' },
        { id: 93, word: 'go to the bathroom', image: '/images/Quick/go_to_bathroom.png', categories_id: 101, tag: 'conjunction' },
        { id: 94, word: 'help', image: '/images/Quick/help.png', categories_id: 101, tag: 'verb' },
        { id: 95, word: 'in', image: '/images/Quick/in.png', categories_id: 101, tag: 'preposition' },
        { id: 96, word: 'I want', image: '/images/Quick/i_want.png', categories_id: 101, tag: 'conjunction' },
        { id: 97, word: 'hello', image: '/images/Quick/hello.png', categories_id: 101, tag: 'noun' },
        { id: 98, word: 'repeat', image: '/images/Quick/repeat.png', categories_id: 101, tag: 'verb' },
        { id: 99, word: 'sorry', image: '/images/Quick/sorry.png', categories_id: 101, tag: 'adjective' },
        { id: 100, word: 'stop', image: '/images/Quick/stop.png', categories_id: 101, tag: 'verb' },
        { id: 101, word: 'bye', image: '/images/Quick/bye.png', categories_id: 101, tag: 'noun' },
        { id: 102, word: 'do not know', image: '/images/Quick/do_not_know.png', categories_id: 101, tag: 'important' },
        { id: 103, word: 'do not want', image: '/images/Quick/do_not_want.png', categories_id: 101, tag: 'important' }
      ])
    })
}
